### ISSUE TITLE
Activesupport installation error

### ISSUE THREAD

**Issue by kjethwani** [wealthbot-io/wealthbot#101]
I've trying to install wealthbot for the past 3 days now and I'm quite close to giving up on it now. While all seems to go well except the activesupport error as seen in the image below. When I access local.wealthbot.io, I'm unable to connect. 

The process I  follow to install is as given by @vlad-ko in another thread
1. clone the repo
2. cd into vagrant dir
3. install the nfs plugin 
4. run vagrant up
5. wait as packages are downloaded and provisioned.
6. vagrant ssh to get into virtual server
7.  edit /etc/hosts file to point server to 192.168.56.105 local.wealthbot.io 

![wealthbot-installation](https://cloud.githubusercontent.com/assets/20903238/19621389/5633601e-98ae-11e6-87cb-9d75fbedccaa.png)

For SSH, I use putty to login. I also tried installing activesupport on Ubuntu after logging in but no avail.

Unable to connect to slack channel as it seems down and also the demo website is down. Any assistance is really appreciated.

Would love to have the development version up. I really wanted to have try out the system so attempted the production version using xampp but I don't think I was doing that right anyway so even that didn't work

**Comment by gkobilansky** [comment]
Did you try upgrading Ruby to version >= 2.2.2. 

Also, you mentioned updating hosts. That should be done on your local machine, not in your virtual machine.

**Comment by kjethwani** [comment]
Thanks for your reply!

I SSHd into the virtual Ubuntu environment using putty and installed the latest version of Ruby. Is that the right thing to do or is there another way to do it?

And since I tried this process a few times now, for every time I made the changes in host file on my local machine under system32/etc/drivers/host and only the last time on both local as well as virtual machine in desperation to get it working.

Really appreciate help to get this work. I wonder what I'm missing here every single time I tried installing it for I get the same error.

**Comment by gkobilansky** [comment]
Sorry, on second thought, that won't work. Updating to Ruby 2.2.2 will probably have unintended downstream effects. Better to update your pupphet config file to use the last version of activesupport that works with Ruby 1.9.3 - https://rubygems.org/gems/activesupport/versions/4.2.7.1

You can do that in your local install at this file - https://github.com/wealthbot-io/wealthbot/blob/master/vagrant/puphpet/config.yaml

Syntax is `{gem}@{version}` per the pupphet docs - https://puphpet.com/#ruby

**Comment by kjethwani** [comment]
Alright so I just added "@4.2.7.1" ahead of activesupport on line number 299 in the file named config.yaml at D:\Programs\GitProjects\wealthbot\vagrant\puphpet

It looks like this now
![config](https://cloud.githubusercontent.com/assets/20903238/19814041/3aaf2d90-9d5a-11e6-8cf1-2209b94b43de.png)

Then I run commands vagrant destroy and vagrant box remove. Then vagrant up. It downloaded all packages again.
However, I continue to get the same error.
![error](https://cloud.githubusercontent.com/assets/20903238/19814150/a854bcb6-9d5a-11e6-8fc2-dcabd9c6d37f.png)

I was really expecting it to work this time.

**Comment by gkobilansky** [comment]
Ah, apparently there's a related bug with pupphet which appeared around June/July. See here -https://github.com/mitchellh/vagrant/issues/7543, specifically here - https://github.com/mitchellh/vagrant/issues/7543#issuecomment-231775954

**Comment by vlad-ko** [comment]
Maybe you could try using an Ami image?

**Comment by kjethwani** [comment]
I'd prefer to try it locally before I have it on cloud. Thing is I don't have an AWS account and will have to sign up with card. If things work then maybe I can take it there and I'm really keen on making it work for it seems to be awesome and one of a kind open source project.

I got around the active support installation problem. thanks for pointing me in the correct direction!
For anybody else facing this problem, here is what I did to solve it.

Apart from adding "@4.2.7.1" in config file like in the screen above, I edited the install-puppet.sh file located at wealthbot/vagrant/puphpet/shell as follows 
Remove
/opt/puppetlabs/puppet/bin/gem install deep_merge activesupport vine --no-ri --no-rdoc
Add
/opt/puppetlabs/puppet/bin/gem install deep_merge  --no-ri --no-rdoc
+/opt/puppetlabs/puppet/bin/gem install activesupport -v 4.2.7.1 --no-ri --no-rdoc
+/opt/puppetlabs/puppet/bin/gem install vine --no-ri --no-rdoc

I, however, get a different set of errors now that I don't know if they happen due to this edit or is there something else. Some dependencies are missing and mongo.
![new error](https://cloud.githubusercontent.com/assets/20903238/19817774/aedc7118-9d6a-11e6-95de-392abb3baf8a.png)

**Comment by gkobilansky** [comment]
Hard to tell what's going on in that screenshot.

**Comment by kjethwani** [comment]
Just edited the comment and updated the image though it is still as messy full of warnings and an error. Thanks for your patience.

**Comment by gkobilansky** [comment]
Yea, I mean I saw those sections before, but they're cut off. Try this - http://stackoverflow.com/questions/27477658/save-putty-ouput-to-file-from-command-line

**Comment by kjethwani** [comment]
I'm sorry but I couldn't quite get that happening. Also, is Putty being used right now since I'm just using windows cmd or git cmd to run commands and this error shows up on the cmd screen itself so how would putty interpret and save it a log unless it is invoked in the process.. This may sound stupid to somebody who understands this obviously but I don't understand it. 
Is there anything else that can be done?
I ran vagrant destroy and vagrant up again. I could get on the Apache2 Debian Default Page reading that it works. It is the default welcome page.

On scrolling through the cmd, there are several errors. The latest of them are that the system could not find a suitable provider for rvm_system_ruby and the same for rvm_gem

**Comment by kjethwani** [comment]
Alright, I just got the Infrastructure team at my company to try the AMI image and we have it up. I can access the super user screen using the public IP. However, on logging in using webo/weboDemo32 nothing really happens. Its like an endless route. Also the same happens on registering RIA and client. 

What could have gone wrong with the image?

**Comment by AdaptFast** [comment]
There is a page on that talks about the endless route that you are experiencing.
**_https://wealthbot.readme.io/docs/getting-stuck-in-redirect-loop-on-admin-login_**

**Comment by kjethwani** [comment]
Thank your time and Reply AdaptFast.

I read that document but as things are right now I gave up on the local installation and we went ahead with AWS image installation as described here. 
https://wealthbot.readme.io/docs/amazon-aws-ami-quick-install

Now one of my colleagues did this installation following the tutorial. I'm not surely how closely it was followed and am lost here. The link you gave talks of a local host installation using Vagrant and virtual box. I don't know how those steps are relevant to the image installation, are they?

**Comment by vlad-ko** [comment]
@kjethwani local install is different. i.e. vagrant install, that's for local env. for the image, is your db populated with data? and is there anything in the users table specifically? you may need to run the post-install command to load fixtures. 
here is where the "demo" user is created, so this needs to be populated and default password hashing should be enabled.
https://github.com/wealthbot-io/wealthbot/blob/master/src/Wealthbot/FixturesBundle/DataFixtures/ORM/LoadAdminData.php#L39

**Comment by kjethwani** [comment]
Thank you for reply. Ok so I just logged into the phpmyadmin and confirmed that the wealthbot database exists with some tables. I couldn't find the users table though so I randomly checked a few tables and there is some data in some of the tables. Like custodians has an entry as follows

14 	TD Ameritrade 	tda@example.com

I'm sorry but I don't understand the part about running post installation commands like how and where. And are they part of standard installation using image? I mean I thought the tutorial was self sufficient and no extra steps were required or is this a special case. 

Thanks for your patience.

**Comment by vlad-ko** [comment]
i'm guessing it's a special case, since a step was probably missed somewhere. generally speaking these "post install" commands should be run automatically by the installer (vagrant or on the image).

you can see the details here from about line 21
https://github.com/wealthbot-io/wealthbot/blob/master/vagrant/puphpet/files/exec-once/webo_setup.sh#L21

this needs to be run in the root of your wealthbot installation

**Comment by vlad-ko** [comment]
@kjethwani if you can't find the users table that's pretty strange. i would expect you to see more errors if a table is missing 😕

**Comment by kjethwani** [comment]
That sounds like a broken or interrupted installation. I didn't know that was possible with an image on AWS. 

All that is accesible right now is the front page with three options to login like the super admin, register ria and register client. On clicking, the respective pages load and then nothing so I guess more errors would come up if it were to go any further but with as many tables as are there in the database right now, maybe it's sufficent for what is accessible right. This is really weird and I feel like a complete noob even htinking about the possibility of such a thing although I do have a background in development earlier on in my career.

I think I'll try reinstalling it tomorrow morning. It's past midnight here and the excitement of replies to this thread have contributed to me staying up haha.

Hopefully, a reinstall should make things fine. Will post the results here.

Thank you again for your help and time.

**Comment by kjethwani** [comment]
Alright so we have the users table now
![user table](https://cloud.githubusercontent.com/assets/20903238/21448496/58b8122c-c909-11e6-9365-5632cc64061b.png)

This is the log file from installation. All seemed ok except two warnings
![install log](https://cloud.githubusercontent.com/assets/20903238/21448523/ae77b550-c909-11e6-970d-3b90c47d0108.PNG)

Tried executing the shell file you pointed out to webo_setup.sh

![running webo shell file](https://cloud.githubusercontent.com/assets/20903238/21448525/c9950676-c909-11e6-9f26-68f0a868042c.png)

Facing the same problem. Unable to login. 
An user by the name sigmasharp faced the same problem as described here
https://github.com/wealthbot-io/wealthbot/issues/91

I don't know how it was solved but you're part of the thread @vlad-ko 
Any idea?

**Comment by AKASH007045** [comment]
I have using the same AMI from AWS i.e;ami-0e03f96e .Every thing goes fine but on the login page after giving the super user credential i.e; webo/weboDemo32 the page is just reloading.
I have also made the tried to login after making the changes in/etc/php5/cli/php.ini file as per specified in https://wealthbot.readme.io/docs/getting-stuck-in-redirect-loop-on-admin-login link..still I am not able to login

 can anyone help me to resolve this error.
thanks

**Comment by joelmccracken** [comment]
Had an issue related to this, ended up applying this patch manually and I was able to move past that problem: https://github.com/puphpet/puphpet/commit/1543dacab766882b969ac49d4635ccfa7c5933ae

**Comment by pandiyanmkm** [comment]
hi all.

can anyone please give a proper guidelines to install a wealthbot in localhost windows (developement) and godaddy (production) server.

i have trying to install using this guidelines ,

https://wealthbot.readme.io/docs/getting-started

but not able to install properly in my local.

kindly advice me

**Comment by azatyan** [comment]
Fixed. please try again.
