### ISSUE TITLE
activesupport requires Ruby version >= 2.2.2. while run ' vagrant provision'

### ISSUE THREAD

**Issue by ldh2068vip** [wealthbot-io/wealthbot#102]
kevins-MacBook-Pro-3:vagrant kevin$ vagrant provision
==> local-webo: Running provisioner: shell...
    local-webo: Running: inline script
==> local-webo: Running provisioner: shell...
    local-webo: Running: /var/folders/rv/_z81z7k503z_973p7l6jyp5w0000gn/T/vagrant-shell20161028-29645-11eeurx.sh
==> local-webo: 
==> local-webo:  ____        ____  _   _ ____      _      generated using
==> local-webo: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> local-webo: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> local-webo: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> local-webo: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> local-webo: 
==> local-webo: Running provisioner: shell...
    local-webo: Running: /var/folders/rv/_z81z7k503z_973p7l6jyp5w0000gn/T/vagrant-shell20161028-29645-1ihxs1g.sh
==> local-webo: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> local-webo: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> local-webo: Adding generated root key to /root/.ssh/id_rsa
==> local-webo: Adding generated root key to /root/.ssh/id_rsa.pub
==> local-webo: Adding generated root key to /root/.ssh/authorized_keys
==> local-webo: Adding generated key to /home/vagrant/.ssh/id_rsa
==> local-webo: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> local-webo: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> local-webo: Running provisioner: shell...
    local-webo: Running: /var/folders/rv/_z81z7k503z_973p7l6jyp5w0000gn/T/vagrant-shell20161028-29645-c33u0e.sh
==> local-webo: Running provisioner: shell...
    local-webo: Running: /var/folders/rv/_z81z7k503z_973p7l6jyp5w0000gn/T/vagrant-shell20161028-29645-1i0svjq.sh
# ==> # local-webo: ERROR:  Error installing activesupport:
_==> local-webo: 	activesupport requires Ruby version >= 2.2.2.
==> local-webo: Successfully installed deep_merge-1.1.1_
==> local-webo: Successfully installed vine-0.2
==> local-webo: 2 gems installed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by gkobilansky** [comment]
Did you try updating your Ruby version >= 2.2.2?

**Comment by gkobilansky** [comment]
Same as issue #101. Closing this one.
