### ISSUE TITLE
Logged into admin panel, now what?

### ISSUE THREAD

**Issue by webierweb** [wealthbot-io/wealthbot#104]
Is there a login for Clients? What is the URL? - Would like to view their portfolio with statistics, etc.

We setup the free version. Is it possible to actually add investments from an outside account and can we do auto rebalancing? How do we set the portfolios and where does this data pull from?

Tutorial of actual use from user end?

**Comment by vlad-ko** [comment]
Data / securities is loaded via fixtures. Or you can make a few models using the ria UI, but that might take a while

Client should be registered​/onboarded first. Then you'll have access to the recommended portfolio and their dashboard. There isn't much for the client to do other than look at balances and allocation of assets.

More advanced features such as account aggregation or automated portfolio rebalancing are not available out of the box. For these features there's a need to integrate with 3rd party services.

**Comment by webierweb** [comment]
Which 3rd party services would you recommend looking at for integration for account aggregation and automated portfolio rebalancing and any other modules that would be needed?

"There isn't much for the client to do other than look at balances and allocation of assets."- Where can the client view this?

**Comment by vlad-ko** [comment]
for account aggregation i would look at blueleaf, byallaccounts and plaid (in no particular order). i'm sure there has been other players launching, since the last time i checked. if yodlee is another option, but afaik they only deal with bank accounts.

for rebalancing i would recommend looking at tradier. (i'm working on "wealthbot connect" which is going to provide that service, but it's a very slow moving project, since i have lots of other obligations).

**Comment by vlad-ko** [comment]
and this blog post will give you some more info on how to load and work with fixtures and how that relates to portfolio creation:
http://blog.wealthbot.io/Updating-Wealthbot-Portfolios/

**Comment by webierweb** [comment]
Thanks. We will investigate this.

Would appreciate any other tips or pointers that you can give so that we can bring this thing to market.

**Comment by vlad-ko** [comment]
hi, to get all the full functionality with automated rebalancing... there's still a fair amount of work remaining. building out those integration is just a matter of writing some code.

there are other issues you should consider: hosting, security, deployment.
you will need to setup Docusign account to allow for digital signatures of various documents.
likely you'll need an smtp server of some sort to be able to send out communication and system emails.

Webo is great starer platform, but it will require additional development work. However, after that you own everything and never have to pay AUM %, monthly fees (other than hosting) and the platform can scale from one client to a thousand without a problem.

p.s. we offer consulting services to help you make the right fintech choice for your business. for example rolling out this project in phases, where you setup customer on-boarding and risk tolerance then plugin rebalancing and other features.

**Comment by azatyan** [comment]
Hi @webierweb  
We updated the Platform, so you can check again and get back with new questions.
Currently we need to create an roadmap and if you can help - we are open
