### ISSUE TITLE
Demo site "Fetal error"

### ISSUE THREAD

**Issue by ittikorns** [wealthbot-io/wealthbot#105]
The demo site isn't available 
http://demo.wealthbot.io/

`Fatal error: Call to undefined function Doctrine\Common\Cache\apc_fetch() in /srv/www/demo.wealthbot.io/core/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php on line 41`

**Comment by vlad-ko** [comment]
thanks fixed.
