### ISSUE TITLE
Mis spelling in AbstractCsvFixture.php causes load:fixtures to fail

### ISSUE THREAD

**Issue by blackdoginet** [wealthbot-io/wealthbot#106]
Mis spelling typo line 23 of src/Wealthbot/FixtureModel/DataBundle/Model/AbstractCsvFixture.php
line 23 WealthBot instead of Wealthbot caues fopen to fail not finding file

**Comment by azatyan** [comment]
Hi.  Just do   doctrine:fixtures:load  doctrine:mongodb:fixtures:load
