### ISSUE TITLE
Wealthbot-io installation not completing

### ISSUE THREAD

**Issue by ankurkansalRobo** [wealthbot-io/wealthbot#107]
Hi
I have tried many times but the installation is not completing....it got stopped at below screenshot. any idea how this can be resolved
![snip20171014_1](https://user-images.githubusercontent.com/32785279/31580295-e9f5aec8-b0ff-11e7-8bef-98db84296f40.png)

**Comment by azatyan** [comment]
Hi @ankurkansalRobo try again with the new code.
