### ISSUE TITLE
Radio buttons are rendering as check boxes

### ISSUE THREAD

**Issue by lahiiru** [wealthbot-io/wealthbot#111]
For the stages > 1.0.0 (stable), radio buttons are rendered as check boxes. Tested on CentOS 7, Ubuntu latest with php 5.6. I'm running app using Symfony built-in server, using dev environment

Example routes,
/client/profile/step-one
/client/profile/step-three

This cause to break javascript queries.

![image](https://user-images.githubusercontent.com/8580134/39669706-64ce6070-5111-11e8-8f3c-b5c2233a84cb.png)

**Comment by azatyan** [comment]
Hello @lahiiru you're right, but currently we plans to rewrite all the system with the new market needs.
So we don't support this version.
Any way, you're open to change the code, fix it and send us an pull request!
https://github.com/wealthbot-io/wealthbot/blob/master/CONTRIBUTING.md

Thank you!

**Comment by lancehaynie** [comment]
If you can give me at least a little guidance I would be happy to take a look. I have never built a project on Symfony and Twig so I am a bit lost as to where to start. Employment on the Client side is doing the same thing. I know it is in the _employment_information_form_type_fields.html.twig file; or at least it is referenced there. But I am unsure of how to change from checkbox to radio.

**Comment by lancehaynie** [comment]
@azatyan @lahiiru I just submitted a pull request that fixes the radio buttons rendering as checkboxes. It also preserves checkboxes that should be checkboxes. 

<img width="435" alt="screen shot 2018-09-17 at 6 01 23 pm" src="https://user-images.githubusercontent.com/30812641/45656631-c7d71f80-baa3-11e8-8126-c49c69aefdc5.png">
<img width="295" alt="screen shot 2018-09-17 at 6 00 58 pm" src="https://user-images.githubusercontent.com/30812641/45656632-c7d71f80-baa3-11e8-9a62-0dbf43ca78c0.png">
<img width="304" alt="screen shot 2018-09-17 at 6 00 25 pm" src="https://user-images.githubusercontent.com/30812641/45656633-c7d71f80-baa3-11e8-8419-98106da4be46.png">
