### ISSUE TITLE
Demo installation with Docker doesn't work

### ISSUE THREAD

**Issue by Thailer86** [wealthbot-io/wealthbot#120]
I did the following steps to setup the appliction:

1. Cloned project from GitHub
2. Run `docker-compose build`
3. Run `docker-compose up -d`
4. Logged in to php container `docker-compose exec php bash`
5. Run `./startup.sh` to fetch composer dependencies, setup the DB and load the fixtures

After this when I access the server, the demo page is shown but nothing works:

- Login pages show up, but when entering the demo account (webo / weboDemo32) page reloads and nothing happens
- For the "Register RIA" page an error is shown immediately: `Type error: Argument 1 passed to Symfony\Component\Form\Form::__construct() must be an instance of Symfony\Component\Form\FormConfigInterface, string given, called in /var/www/symfony/var/cache/dev/ContainerOjssrvt/getWealthbotUser_Registration_Ria_FormService.php on line 8` 
and
`Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Component\Form\Form::__construct() must be an instance of Symfony\Component\Form\FormConfigInterface, string given, called in /var/www/symfony/var/cache/dev/ContainerOjssrvt/getWealthbotUser_Registration_Ria_FormService.php on line 8" at /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 168`
as well as the following Info: 
`User Deprecated: The "wealthbot_user.registration.ria.form" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`
- for the "Register Client" first the RIA with id 14 is not found. If I change to 6 I get the same exceptions as mentioned above.

**Comment by vlad-ko** [comment]
@Thailer86 , we are in the process of upgrading the project from symfony2 to symfony3, I expect things to be unstable at the moment. (Also moving things from vagrant to docker, docker-compose).

Maybe @azatyan has a few minutes to help you out. I will be traveling until Jan 31st and hopefully we'll resume work after that. If you are interested in contributing please email me at hi {at} wealthbot.io.

**Comment by chibsta** [comment]
@azatyan have the forms been sorted yet? I was able to successfully install 1.1.0 branch but there are a number of errors I was not able to resolve. When do you think the new version will be out?

**Comment by Thailer86** [comment]
+1 I am also interested.
I am anyway wondering, wouldn't it be best practice to develop such major changes on the "develop" branch and only merge working software into the master, so master is always stable and working?

**Comment by azatyan** [comment]
Ill try  to resolve docker issue

**Comment by vlad-ko** [comment]
@Thailer86 we had issues with master because it was very much outdated and things weren't really working. hopefully we'll be able to slowly, but sure upgrade things so the project actually goes back to a stable state. 
By the way, if you are interested in contributing to the project, please let me know.

**Comment by bigdatamlai** [comment]
guys, 
Is any of branchs working? I was able to deploy master but not able to install 
.bin/console doctrine:schema:create
on develop branch i ran "docker-compose exec php bash"
and start.sh
"wealthbot_user.registration.ria.form.handler" has a dependency on a non-existent service "request".
Any ideas what i could deploy on my mac to play with it, and what steps i need to follow?

**Comment by bigdatamlai** [comment]
i was able to do on master
docker-compose build
docker-compose up
./ startup.sh
docker-compose exec php bash
got no exception, and the site is up, but I am not able to login in, what i am missing?

**Comment by vlad-ko** [comment]
@bigdatamlai i think you still need to run `composer`, create schema and load the fixtures so you have some preliminary data.
The commands should be at the bottom of Readme. 

It would be great if you could update Readme, if you find that some info is missing or inaccurate. Thanks.

**Comment by bigdatamlai** [comment]
@vlad-ko 
after docker-compose up -d
i ran "docker-compose exec php bash"
and ./startup.sh
I also ran bin/console doctrine:schema:create and bin/console wealthbot:fixtures:load
 Which command should i run with composer? i ran "composer install"
root@f210f9cbce55:/var/www/symfony# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpoffice/phpspreadsheet 1.6.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - phpoffice/phpspreadsheet 1.6.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for phpoffice/phpspreadsheet 1.6.0 -> satisfiable by phpoffice/phpspreadsheet[1.6.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/tzone.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
root@f210f9cbce55:/var/www/symfony#

**Comment by vlad-ko** [comment]
@bigdatamlai .. eh, looks like GD is missing. we probably didn't test properly the new docker setup. it's possible we just need to install php-gd (http://php.net/manual/en/image.installation.php) here:
https://github.com/wealthbot-io/wealthbot/blob/master/docker/php-fpm/Dockerfile#L19

i actually thought it was enabled by default nowadays. anyways, that might help to get further along once GD is enabled in the php container. unfortunately I am at work and won't be able to test this. if that's something you can try on your local i would appreciate it.

**Comment by azatyan** [comment]
Currently,
we are upgrading Webo to Symfony version 4.4
