### ISSUE TITLE
Demo site is unavailable

### ISSUE THREAD

**Issue by jzebedee** [wealthbot-io/wealthbot#121]
Visiting http://demo.wealthbot.io/ fails to resolve.

https://downforeveryoneorjustme.com/demo.wealthbot.io also shows unavailable

Wayback machine shows a working version about a year ago, March 2018.
https://web.archive.org/web/20180324225808/http://demo.wealthbot.io/

**Comment by NicksonYap** [comment]
Down for me too

**Comment by vlad-ko** [comment]
Unfortunately the demo has been down for a while, the project has been in limbo for a few years and we need to upgrade things (which we are slowly doing right now). 

If anyone is interested in contributing / helping out please let me know hi [at] wealthbot.io

**Comment by chibsta** [comment]
Hi @vlad-ko. I am interested in helping as I believe that this product has a lot of potential. I tied emailing hi@wealthbot.io but I the email is not going through.

**Comment by skorokithakis** [comment]
Hey @chibsta, the project is in the [Code Shelter](https://www.codeshelter.co/) so you can also contact us if you want to help out.

**Comment by azatyan** [comment]
http://demo.wealthbot.io  available for now :)
