### ISSUE TITLE
RIA custom url (not working | dont know how)

### ISSUE THREAD

**Issue by jeraldfeller** [wealthbot-io/wealthbot#122]
![image](https://user-images.githubusercontent.com/16371225/64597649-bd1a4680-d3e8-11e9-833e-37a9a2a33d1f.png)

On RIA profile there is a custom url field as on my understanding it will be {custom-url}.wealthbot.io
but the custom url doesnt work.

**Comment by azatyan** [comment]
hi @jeraldfeller , this part is not yet implemented in new version, as this is a secondary feature than others.

If you can - we love pull requests.

**Comment by CMarik** [comment]
All errors associated with Wealthbot have now been fixed. Webo is currently working and stable! Follow our ReadMe file located [here](https://github.com/wealthbot-io/wealthbot) and have fun! Any inquiries email us at hi@wealthbot.io and we will respond promptly.
