### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by azatyan** [wealthbot-io/wealthbot#123]
Dear community,

We need to create a roadmap for development.
Please test platform with URL:  http://demo.wealthbot.io
And get back with advises and questions

Thank you in advance,
Tigran

**Comment by hakimomar** [comment]
Do you have a clear guide and prerequisites compatible to each other on installing wealthbot?

**Comment by azatyan** [comment]
Hi @hakimomar 
Thank you for submitted bugs and comments.

**Comment by hakimomar** [comment]
Hello,

Please have you had any chance to look into this and help me?

I will appreciate the response.

Thank you!

Omar Hakim

**Comment by vlad-ko** [comment]
N/A, we'll be relaunching soon. stay tuned.
