### ISSUE TITLE
Portfolio Unable to Find Template

### ISSUE THREAD

**Issue by hakimomar** [wealthbot-io/wealthbot#124]
![wealthbot](https://user-images.githubusercontent.com/57633986/68602720-87104600-04af-11ea-9c1a-2e3d2fe9317b.JPG)

I think the main issue is 
PHP Warning:  PHP Startup: Unable to load dynamic library 'twig.so' (tried: /usr/lib64/php/modules/twig.so (/usr/lib64/php/modules/twig.so: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/twig.so.so (/usr/lib64/php/modules/twig.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Can someone help me with this?
I have been trying to solve this for weeks now.
I am installing wealthbot on Centos 7, phpv7.3

**Comment by hakimomar** [comment]
@azatyan Do you have a suggestion or a solution for this?

**Comment by CMarik** [comment]
All errors associated with Wealthbot have now been fixed. Webo is currently working and stable! Follow our ReadMe file located [here](https://github.com/wealthbot-io/wealthbot) and have fun! Any inquiries email us at hi@wealthbot.io and we will respond promptly.

**Comment by azatyan** [comment]
Thank you all @CMarik
