### ISSUE TITLE
Symfony Authentication Error

### ISSUE THREAD

**Issue by hakimomar** [wealthbot-io/wealthbot#125]
![symfony](https://user-images.githubusercontent.com/57633986/68614102-e890de80-04c8-11ea-9f5f-a9ac05226350.JPG)
Does anyone have any idea how can I get over this?
I am installing php7.3.11 on debian 9 and symfony v4.9.0.

**Comment by rogerlz** [comment]
I got this issue as well and it seems that TokenStorage should be replaced by TokenStorageInterface. I changed the code to that, but I still can't get the login process to work. 

The next issue is with checkIsPasswordExpired, which receives a null $user for some reason.

**Comment by CMarik** [comment]
Good Evening,

All errors associated with Wealthbot have now been fixed. Webo is currently working and stable! Follow our ReadMe file located [here](https://github.com/wealthbot-io/wealthbot) and have fun! Any inquiries email us at hi@wealthbot.io and we will respond promptly.
