### ISSUE TITLE
status of the project?

### ISSUE THREAD

**Issue by rogerlz** [wealthbot-io/wealthbot#126]
is it still alive? does the author still have plans to keep it going?

**Comment by skorokithakis** [comment]
The project is in the [Code Shelter](https://www.codeshelter.co/), so it's "help wanted", basically.

**Comment by azatyan** [comment]
Status is help wanted,
Anyone can join and make PR's to help project.

**Comment by vlad-ko** [comment]
making some updates basic functionality is back online.
