### ISSUE TITLE
Error while installing the project error-renderer

### ISSUE THREAD

**Issue by SalmanAhmadButt** [wealthbot-io/wealthbot#127]
`user@system:~/Desktop/htdocs/wealthbot$ symfony composer install --ignore-platform-reqs
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 112 installs, 0 updates, 0 removals
  - Installing symfony/error-renderer (dev-master 6ae9c0d): Downloading (failed)    Failed to download symfony/error-renderer from dist: The "https://api.github.com/repos/symfony/error-renderer/zipball/6ae9c0d50a7e4568d5e269ec3e852f10630ac200" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing symfony/error-renderer (dev-master 6ae9c0d): Username for 'https://github.com': [github username]
Password for 'https://[github username]@github.com': 
Cloning 6ae9c0d50a
Username for 'https://github.com': [github username]
Password for 'https://[github username]@github.com': 

In Git.php line 325:
                                                                                                     
  Failed to clone https://github.com/symfony/error-renderer.git via https, ssh protocols, aborting.  
                                                                                                     
  - https://github.com/symfony/error-renderer.git                                                    
    Cloning into '/opt/lampp/htdocs/wealthbot/vendor/symfony/error-renderer'...                      
    remote: Invalid username or password.                                                            
    fatal: Authentication failed for 'https://github.com/symfony/error-renderer.git/'                
                                                                                                     
  - git@github.com:symfony/error-renderer.git                                                        
    Cloning into '/opt/lampp/htdocs/wealthbot/vendor/symfony/error-renderer'...                      
    ERROR: Repository not found.                                                                     
    fatal: Could not read from remote repository.                                                    
                                                                                                     
    Please make sure you have the correct access rights                                              
    and the repository exists.                                                                       
                                                                                                     

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

unable to run /usr/bin/composer install --ignore-platform-reqs: exit status 1
`

**Comment by piaoxj** [comment]
same problem

**Comment by ccodelover** [comment]
same, so no solution?

**Comment by CMarik** [comment]
We are aware of this issue and are currently working on a solution. We will keep you updated.

**Comment by vlad-ko** [comment]
This is fixed in the latest upgrade.
