### ISSUE TITLE
Fix ria user managment section

### ISSUE THREAD

**Issue by vlad-ko** [wealthbot-io/wealthbot#18]
When creating users/group for a fresh RIA account, we are seeing problems with ajax/db.

**Comment by azatyan** [comment]
Please check.

**Comment by CMarik** [comment]
All errors associated with Wealthbot have now been fixed. Webo is currently working and stable! Follow our ReadMe file located [here](https://github.com/wealthbot-io/wealthbot) and have fun! Any inquiries email us at hi@wealthbot.io and we will respond promptly.
