### ISSUE TITLE
Error when trying to view portfolio 

### ISSUE THREAD

**Issue by dunnston** [wealthbot-io/wealthbot#42]
This is most likely due to incomplete or invalid data. Before getting the error I created a new asset class but no sub classes. Then I tried to add a security but it didn't save. Finally, I attempted to add a new allocation. After saving a new allocation I got the error. 

Now every time I try to navigate to the portfolios screen I get the following error:

Impossible to access an attribute ("assetClass") on a null variable in WealthbotRiaBundle:Securities:model_securities_list.html.twig at line 78

**Comment by CMarik** [comment]
All errors associated with Wealthbot have now been fixed. Webo is currently working and stable! Follow our ReadMe file located [here](https://github.com/wealthbot-io/wealthbot) and have fun! Any inquiries email us at hi@wealthbot.io and we will respond promptly.
