### ISSUE TITLE
Install on linux server

### ISSUE THREAD

**Issue by akhilrs** [wealthbot-io/wealthbot#50]
Is it possible to install wealthbot in linux server without using vagrant/virtualbox ?

**Comment by vlad-ko** [comment]
yes, you need full LAMMP stack setup and then you need follow the commands similar to the ones run by vagrant:
https://github.com/wealthbot-io/wealthbot/blob/master/vagrant/puphpet/files/exec-once/webo_setup.sh

(start from line 12, where you run composer install)
