### ISSUE TITLE
Super admin login issue

### ISSUE THREAD

**Issue by akhilrs** [wealthbot-io/wealthbot#51]
I configured everything in Ubuntu 14.04 server without using vagrant, but now I am unable to login as super admin using the demo admin details webo/weboDemo32. When I hit login form submit button it just  redirect to /admin/login, nothing happens. 
In app/logs/dev.log I got `security.INFO: Authentication request failed: Your session has timed out, or you have disabled cookies. [] []`. I tried in both Chrome and Firefox with cookies enabled but no helps. 
I also checked PHP `session_save_path` permission and everything works fine there.
Can I know what may causing this issue?

**Comment by vlad-ko** [comment]
did you load fixtures?

you need to run post-install commands that would be run by vagrant here:
https://github.com/wealthbot-io/wealthbot/blob/master/vagrant/puphpet/files/exec-once/webo_setup.sh

**Comment by akhilrs** [comment]
Yes, I loaded fixtures and everything looks good in database also

**Comment by vlad-ko** [comment]
hmm at this point my knowledge is limited to googling, i'm sure you've seen these references:
http://stackoverflow.com/questions/9880943/symfony-authentication-cant-get-past-login-page-in-production

looks to be symfony related config, unfortunately i can't offer much more help.

**Comment by akhilrs** [comment]
Yes you are right, I already tried everything given in that reference.
Quick question - If I upgrade symfony 2.1 to the latest stable version, will it break anything?

**Comment by vlad-ko** [comment]
yeah, there are some things that need to be changed due to BC in symfony... i'm currently working on upgrade in feature/symfony-upgrade (to upgrade to 2.3). eventually my goal is to have it working on 2.7, but gotta tackle the 2.3 upgrade first. )

cheers

**Comment by akhilrs** [comment]
Thumbs up for that :+1: Hope you can done that real soon :)

**Comment by gkobilansky** [comment]
Closing, because master branch is updated to Symfony 2.8

**Comment by strongman1995** [comment]
maybe the site-domain in  the app/config/parameter.yml is not yours. change it . save it. and fix it.

**Comment by webierweb** [comment]
I installed wealthbot using the Amazon EC2 instance.

Installed here. Unable to login:

http://54.214.26.81/admin/login


How do I fix that?

**Comment by azatyan** [comment]
Enter IP address as site name in parameters.yml
