### ISSUE TITLE
User Management Edit Button

### ISSUE THREAD

**Issue by dlojac** [wealthbot-io/wealthbot#52]
Navigation: RIA -> Create users and user groups. -> User Management

"Edit" button next to user loads indefinitely after being clicked.

**Comment by CMarik** [comment]
All errors associated with Wealthbot have now been fixed. Webo is currently working and stable! Follow our ReadMe file located [here](https://github.com/wealthbot-io/wealthbot) and have fun! Any inquiries email us at hi@wealthbot.io and we will respond promptly.
