### ISSUE TITLE
Group Management Submit Button

### ISSUE THREAD

**Issue by dlojac** [wealthbot-io/wealthbot#53]
Navigation: RIA -> Create users and user groups. -> Group Management

"Submit" button at the bottom of the page loads indefinitely after being clicked.

**Comment by JohnnyLe** [comment]
It happens same to me too. Did you find any solution for that?

**Comment by azatyan** [comment]
Can you write which error throws in console.?

**Comment by JohnnyLe** [comment]
It shows 500 internal error at api /ria/user/create, like image bellow

![image](https://cloud.githubusercontent.com/assets/1794584/16072138/869a3dc8-3309-11e6-80b1-73b234e5b9ab.png)

**Comment by strongman1995** [comment]
Notice: Undefined variable: riaUser in /opt/bitnami/apps/wealthbot/src/Wealthbot/RiaBundle/Controller/UserController.php line 103

500 Internal Server Error - ErrorException

Stack Trace

in /opt/bitnami/apps/wealthbot/src/Wealthbot/RiaBundle/Controller/UserController.php at line 103   -
        return $this->render('WealthbotRiaBundle:User:edit.html.twig', array(
            'form' => $form->createView(),
            'ria_users' => $riaUsers,
            'ria_user' => $riaUser,
            'ria' => $ria
        ));
    }
