### ISSUE TITLE
Client Tab on RIA dashboard missing data

### ISSUE THREAD

**Issue by gkobilansky** [wealthbot-io/wealthbot#70]
To reproduce in demo instance:
1. Login as Mortal Kombat Advisors
2. Navigate to Clients tab
3. No data is shown, even though MK has registered clients

![wealthbot_io_and_wealthbot_io](https://cloud.githubusercontent.com/assets/1930015/11275578/411c3956-8eac-11e5-8052-7d10c9dff860.png)

**Comment by azatyan** [comment]
This is fixed.
