### ISSUE TITLE
[Insight] Exceptions should not be enabled in production - in web/app.php, line 8

### ISSUE THREAD

**Issue by vlad-ko** [wealthbot-io/wealthbot#75]
**[in web/app.php, line 8](https://github.com/wealthbot-io/wealthbot/blob/8ab560810a3d5347e412bcc6f071bb2156691df0/web/app.php#L8)**

> This production application kernel is initialized in debug mode (second parameter to `true`, which allows the display of exceptions.

```php
/**
 * @var Composer\Autoload\ClassLoader
 */
$loader = require __DIR__.'/../app/autoload.php';
include_once __DIR__.'/../app/bootstrap.php.cache';
$kernel = new AppKernel('prod', true);
$kernel->loadClassCache();
//$kernel = new AppCache($kernel);
// When using the HttpCache, you need to call the method in your front controller instead of relying on the configuration parameter
//Request::enableHttpMethodParameterOverride();
$request = Request::createFromGlobals();
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/5b9cb5eb-6a34-4e87-a9cf-eb6f69638e6a/analyses/37)_

**Comment by azatyan** [comment]
This can be closed after merging 2.8 branch.!
