### ISSUE TITLE
Upgrade source code

### ISSUE THREAD

**Issue by JohnnyLe** [wealthbot-io/wealthbot#89]
Hi team,

I already deploy a version in the last and have some data. Now I would like to update the source code to latest version in master branch. Do you have and advise for me to avoid issue when upgrade? Or just replace PHP code file is ok?  And the master branch is running stable now?
That would be great you can create a tag for each update version.

Thank you for your support.

Best regards
Johnny

**Comment by azatyan** [comment]
@JohnnyLe tags will be done, thanks.

**Comment by JohnnyLe** [comment]
Great! Thank you.

**Comment by azatyan** [comment]
@JohnnyLe we will provide complete upgrade how-to document today.
