### ISSUE TITLE
Custodians - download file error

### ISSUE THREAD

**Issue by JohnnyLe** [wealthbot-io/wealthbot#90]
Click on tab "Custodians" Save (upload) => OK 
![image](https://cloud.githubusercontent.com/assets/1794584/16004883/872bfa6e-318e-11e6-96df-cf6699d76a41.png)

But after click download it show error, actually the file is existed in server. 

![image](https://cloud.githubusercontent.com/assets/1794584/16004928/bb02f86a-318e-11e6-827d-cc9b91037ee0.png)

Do you have any idea how to fix it?

**Comment by azatyan** [comment]
This is fixed since new version with Symfony4
