### ISSUE TITLE
AWS AMI quick deployment

### ISSUE THREAD

**Issue by JohnnyLe** [wealthbot-io/wealthbot#91]
Just share public aws ami, build from master branch (5.9.2016) AMI ID: ami-0e03f96e 
So anyone can have a quick try with it in your own server.

**Comment by sigmasharp** [comment]
Many thanks Johnny, but is it available in AWS's EC2 AMI list?  I tried to search for it but could not find it as AMI ID: ami-0e03f96e...  Thanks

**Comment by sigmasharp** [comment]
Hi Johnny, don't bother I found it, it is in the Oregon area

**Comment by sigmasharp** [comment]
Thank you so much again, Johnny.  It's a great starting point!!!

Though all LAMMP looks up and running, I can't seem to be able to pass any log in points. Neither the default super admin or trial registered client account log-in works.  I even tried to change part of the php code to revise the default login but there is just no further responses on the log in page.

Any tips will be highly appreciated..

**Comment by JohnnyLe** [comment]
Already response your email.

**Comment by sigmasharp** [comment]
Many thanks, Johnny.

**Comment by vlad-ko** [comment]
@JohnnyLe could you leave the instructions on getting the AMI image here or email to hi [at] welathbot.io , we'd love to add it to our official set of installation options. All of your work will be properly credited. 

Thank you

**Comment by JohnnyLe** [comment]
Hi @vlad-ko 

Ok, so please create a wiki page for instructions installation then i can support update in that.
It seem create in issue List is hard to find it when many topics open.
Btw, do we have anyone in your team create guideline for upgrade code when new version release.
So base on that I can support you guys to update AMI when there are new release as well.

Best regards
Johnny

**Comment by gkobilansky** [comment]
Hi @JohnnyLe. Here is the doc for how to upgrade to the latest version - https://github.com/wealthbot-io/wealthbot/blob/master/UPGRADE.md

We use https://wealthbot.readme.io/ as documentation wiki. I think we can add the AMI steps here - https://wealthbot.readme.io/docs/getting-started

**Comment by JohnnyLe** [comment]
Hi @gkobilansky 

I take some notes for AWS deployment as bellow, so you can add it into your wiki. 
----------------------------------------------
##### Step 1: Login into AWS console and select EC2 to launch new instance.
![image](https://cloud.githubusercontent.com/assets/1794584/16550842/8c6d50ca-41da-11e6-85dc-8a5bbb7b8f96.png)

##### Step 2: Under AMI menu tab, search public AMI (ami-0e03f96e) as bellow, the click launch button.

![image](https://cloud.githubusercontent.com/assets/1794584/16550918/a8c8870c-41db-11e6-9f13-be9f93868137.png)

##### Step 3: Launch new instance from AMI (ami-0e03f96e). Follow the step from aws console, Security Group should be enable at least port 80 & 22.
![image](https://cloud.githubusercontent.com/assets/1794584/16551012/e06ccb86-41dc-11e6-96e4-b10f0298b44a.png)

Type keypair name, download your keypair and click Launch
![image](https://cloud.githubusercontent.com/assets/1794584/16551078/fa0b5b42-41dd-11e6-81c8-00bbd474f424.png)

##### Step 4: Access the app, after launched successful the AMI, you will see the public IP to access the app as bellow
![image](https://cloud.githubusercontent.com/assets/1794584/16551176/2a19214c-41df-11e6-9a0b-5071239b2414.png)

And it's ready to go.
![image](https://cloud.githubusercontent.com/assets/1794584/16551195/5b9f2dec-41df-11e6-9529-c0b4d6067bd8.png)

This AMI also included phpmyadmin so after launched you can access phpmyadmin as url http://{your IP}/phpmyadmin. the default account (root/pss1@#)

##### Other note:

- This AMI was built base on Bitnami LAMP stack, so for more information to use this AMI, please checkout the document here 
https://wiki.bitnami.com/Components/Apache
- If you got some issues with SMTP mail server, you can install SMTP server in this EC2 very easy with Posfix by follow these steps 
https://www.digitalocean.com/community/tutorials/how-to-install-and-setup-postfix-on-ubuntu-12-04

Good luck!

--------------------------------------

**Comment by vlad-ko** [comment]
Thanks @JohnnyLe !!

this is great. i'm sure this will be a great benefit to the webo community.

cheers

**Comment by gkobilansky** [comment]
@JohnnyLe you are the man! I upgdated the wiki - https://wealthbot.readme.io/v1.1.0/docs/amazon-aws-ami-quick-install

Will respond to your email shortly.

**Comment by webierweb** [comment]
Searching in EC2 for ami-0e03f96e, not coming up. Someone says it is in the Oregon location?? How to find wealthbot easy installer?

**Comment by webierweb** [comment]
I figured it out.

**Comment by JohnnyLe** [comment]
Hi @webierweb 

Sorry for late response. Glad to hear you already found & run it.

**Comment by webierweb** [comment]
The super admin logs just reloads the page. How can we apply these changes to EC2?

https://wealthbot.readme.io/docs/getting-stuck-in-redirect-loop-on-admin-login

**Comment by john-burkedublin** [comment]
Hello @JohnnyLe 
I was trying to search for "ami-0e03f96e" in EC2 under location Oregon on AWS but can't seem to find it.
Am I missing something or has something changed and the instructions are no longer valid?

Many Thanks!

**Comment by john-burkedublin** [comment]
Hi @JohnnyLe 
Here is the screenshot for the above problem.
Many Thanks!
J Burke
<img width="898" alt="Screenshot 2019-11-08 at 13 29 11" src="https://user-images.githubusercontent.com/57531595/68480052-c6c6fb80-022b-11ea-8bf7-43516572ed32.png">
