### ISSUE TITLE
Fatal error on production.

### ISSUE THREAD

**Issue by idenkov** [wealthbot-io/wealthbot#94]
I am getting fatal error when trying to install in virtual machine fallowing your production installation guide from http://wealthbot.io/install.html

`[Wed Jul 06 03:12:15.835054 2016] [:error] [pid 27415] [client 192.168.122.1:54478] PHP Warning:  require(/var/www/wealthbot/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wealthbot/app/autoload.php on line 7
[Wed Jul 06 03:12:15.835592 2016] [:error] [pid 27415] [client 192.168.122.1:54478] PHP Fatal error:  require(): Failed opening required '/var/www/wealthbot/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/wealthbot/app/autoload.php on line 7
`

Machine is Ubuntu 16.04
Apache with php 7.0.6(tested with 5.6 too), mongo driver, mod rewrite.

**Comment by boatsetter** [comment]
Seems like composer didn't setup properly.

Please try running composer update in the root of webo

**Comment by idenkov** [comment]
Should I add these "codes" to the composer.json? I am kind of lost.

**Comment by idenkov** [comment]
I gave up on this. It is nightmare to make it run with the dependecy/version bloat between mongo, mongo driver, symfony, composer.
