### ISSUE TITLE
AMI does not work

### ISSUE THREAD

**Issue by venkatsethu** [wealthbot-io/wealthbot#99]
Hi, 
The amazon public AMI id is not available to choose in AWS EC2. Is there a different id that can be accessed for quick launch on aws. Appreciate to know

**Comment by gkobilansky** [comment]
I was able to find it no problem. Did you search public AMIs? See attached screenshot.

![screen shot 2016-09-20 at 3 21 38 pm](https://cloud.githubusercontent.com/assets/1930015/18685448/0e2ec94c-7f46-11e6-9da6-8c2b090150f3.png)

**Comment by venkatsethu** [comment]
Hi Thanks. I find it only in Oregan Data center. Can it be provided in 
Mumbai Data center?

I fired it up but got stuck in Login. Neither the Super Admin (with 
*webo/weboDemo32) works *(nor) Register RIA with one's own created 
password works.

How do I get to login in as Super admin or Register RIA as nothing seems 
to happen on the browser after pressing. It just shows the same screen 
once again.*
*

Best regards,

*Sethu V*

*eesysite*

10, Meenakshi st, Perambur, Chennai 600011, TN, India

M: +91 98840 83363 | T: +91 44 4214 5981

E: svr@eesysite.com | W: www.eesysite.com | http://eesysite.in

*Business Consulting | IT Infrastructure | IT Applications*

**Comment by gkobilansky** [comment]
[Launch Public AMI from one EC2 region in another](http://serverfault.com/questions/506528/launch-public-ami-from-one-ec2-region-in-another) should give you an idea how to handle moving AMIs. 

You server setup problem sounds like a separate issue. Please review the [contribution guidelines](https://github.com/wealthbot-io/wealthbot/blob/master/CONTRIBUTING.md) and open a new issue.
